### ISSUE TITLE
This repository name is mis-spelled

### ISSUE THREAD

**Issue by walterdavis** [mindaslab/phoenixbricks#3]
pheonix vs phoenix -- you refer to the latter (correctly) throughout the Rubygems metadata, but this repo is named the bad way. It's early days, so it should be fix-able (don't have 10,000 inbound links to worry about).

Walter

**Comment by fwolfst** [comment]
Oups...
+1 !

**Comment by mindaslab** [comment]
Done ;) Thanks.
